swagger: "2.0"
info:
  version: "1.0.0"
  title: "API del Carrito"
paths:
  /carts/{cid}:
    get:
      summary: "Obtener un carrito por ID"
      parameters:
        - in: path
          name: cid
          required: true
          type: string
      responses:
        "200":
          description: "Carrito obtenido exitosamente"
        "400":
          description: "Datos insuficientes"
        "404":
          description: "Carrito no encontrado"
        "500":
          description: "Error interno del servidor"
    post:
      summary: "Crear un nuevo carrito"
      responses:
        "201":
          description: "Carrito creado exitosamente"
        "500":
          description: "Error interno del servidor"
    delete:
      summary: "Eliminar un carrito por ID"
      parameters:
        - in: path
          name: cid
          required: true
          type: string
      responses:
        "200":
          description: "Carrito eliminado exitosamente"
        "400":
          description: "Datos insuficientes"
        "500":
          description: "Error interno del servidor"
    put:
      summary: "Actualizar un carrito por ID"
      parameters:
        - in: path
          name: cid
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              products:
                type: array
                items:
                  type: string
      responses:
        "200":
          description: "Carrito actualizado exitosamente"
        "400":
          description: "Datos insuficientes"
        "500":
          description: "Error interno del servidor"
  /carts/{cid}/products/{pid}:
    post:
      summary: "Agregar un producto a un carrito"
      parameters:
        - in: path
          name: cid
          required: true
          type: string
        - in: path
          name: pid
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              quantity:
                type: integer
      responses:
        "201":
          description: "Producto agregado al carrito exitosamente"
        "400":
          description: "Datos insuficientes"
        "500":
          description: "Error interno del servidor"
    delete:
      summary: "Eliminar un producto de un carrito"
      parameters:
        - in: path
          name: cid
          required: true
          type: string
        - in: path
          name: pid
          required: true
          type: string
      responses:
        "200":
          description: "Producto eliminado del carrito exitosamente"
        "400":
          description: "Datos insuficientes"
        "500":
          description: "Error interno del servidor"
    put:
      summary: "Actualizar la cantidad de un producto en un carrito"
      parameters:
        - in: path
          name: cid
          required: true
          type: string
        - in: path
          name: pid
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              quantity:
                type: integer
      responses:
        "200":
          description: "Cantidad de producto actualizada exitosamente"
        "400":
          description: "Datos insuficientes"
        "500":
          description: "Error interno del servidor"
  /carts/{cid}/purchase:
    post:
      summary: "Realizar una compra"
      parameters:
        - in: path
          name: cid
          required: true
          type: string
      responses:
        "200":
          description: "Compra realizada exitosamente"
        "400":
          description: "Datos insuficientes"
        "500":
          description: "Error interno del servidor"
